version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:9202fc6bc8fa63615e6bfc0049fc660f712d164220c5c54d86519870c305ea48
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  redis:
    image: redis:7@sha256:e50c7e23f79ae81351beacb20e004720d4bed657415e68c2b1a2b5557c075ce0
    ports:
      - '6377:6379'

  localstack:
    image: localstack/localstack@sha256:3e9fd1c7feb67dd300041f4c756274d26b63f4875b1571574d536660a13c0f27
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8080:8080'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:18@sha256:370db2cf5b89acc950805ef32aa9cbfc69d86769f92ba9f3492a36a6f75e0d92
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4029:4029'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm i && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
      - redis
