version: '3.8'
services:
  mysql:
    image: mysql:5.7@sha256:f57eef421000aaf8332a91ab0b6c96b3c83ed2a981c29e6528b21ce10197cd16
    env_file:
      - ./.docker/local.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    platform: linux/amd64
    ports:
      - '3306:3306'

  redis:
    image: redis:7@sha256:f50031a49f41e493087fb95f96fdb3523bb25dcf6a3f0b07c588ad3cdbe1d0aa
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack@sha256:5b5e903ac421fb9c065f5df4dbdc737c7c77571011b2d3ad4d9d81c7c3ed703a
    env_file:
      - .docker/local.env
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:4566/_localstack/health
      interval: 5s
      timeout: 10s
      start_period: 10s
    platform: linux/amd64
    ports:
      - '4566:4566'
      - '8080:8080'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d

  otlpcollector:
      image: amazon/aws-otel-collector@sha256:a94db15e754ce67149d67c0a6f366bec3fa93b59626757a1436d3fb833f7cafc
      command: --config=/etc/ecs/ecs-default-config.yaml --set=service.telemetry.logs.level=debug
      env_file:
        - .docker/local.env
      ports:
        - '4137:4137'
        - '4138:4138'

  app:
    # Debian GNU/Linux 11 (bullseye)
    image: node:18-slim@sha256:2ff9841de879f1a2d2d8ef83183c2d93435c451a36d6cfb37b3331d1386c00f8
    command: "bash -c 'cd /app && npm i && npm run start:dev'"
    depends_on:
      localstack:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      otlpcollector:
        condition: service_started
    env_file:
      - .docker/local.env
    environment:
      - NODE_ENV=local
    platform: linux/amd64
    ports:
      - '4029:4029'
    volumes:
      - ./:/app
    working_dir: /app
